management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
  #      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  server:
    port: 8080

info:
  app:
    name: hello-actuator
    company: sh

logging:
  level:
    com.openmpy.actuator.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true